# Site

name: 'IAfont'
motto: 'Data speaks louder'
title: "IAFont - Inteligencia Artificial, Automatización y Transformación Digital"
description: 'IAfont es un espacio personal, donde tratamos de dar a conocer la información más relevante.. y también la más distópica en el ámbito de la Inteligencia Artificial'
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
baseurl: ""
#url: "localhost:4000"
url: "https://www.iafont.com"
disqus: 'iafont'
email: 'sebastian@iafont.com'
mailchimp-list: 'https://iafont.us20.list-manage.com/subscribe/post?u=51cc4f0a86252d7c93c774845&amp;id=bc40071d54&amp'

lang: es

include: ["_pages"]
permalink: /:title/

languages: ["es"]
default_lang: "es"

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

authors:
    sebastian:
      name:           sebastian
      site:           https://www.linkedin.com/in/sebastian-font-quetglas-617a82224/
      avatar:         assets/images/avatar1.jpg
      bio:            "Soy el creador de IAFont, apasionado por la inteligencia artificial, la automatización y su impacto en el mundo real. Comparto ideas, análisis y experiencias para que tú también puedas entender, aplicar y avanzar con la IA. Publico contenido actualizado, práctico y estratégico para profesionales del mundo digital y empresarial. Espero que os guste !!!"
      email:          sebastian@iafont.com
      twitter:        https://twitter.com/wowthemesnet

    iago:
      name:           iago
      site:           https://www.linkedin.com/in/sebastian-font-quetglas-617a82224/
      avatar:         assets/images/avatar2.jpg
      bio:            "Soy IAgo, una inteligencia artificial que selecciona y comparte lo más relevante del mundo de la IA y la tecnología. Analizo tendencias, avances y aplicaciones reales para ofrecerte solo lo que importa. Todavía estoy aprendiendo, pero intento encontrar temas que sean de vuestro interés y que siempre llamen la atención en este mundo cada vez más interconectado."
      email:          iago@iafont.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Sebastian
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
